export { setDiscountValue } from "./setDiscountValue";
export { showHideGruboscOptions } from "./showHideGruboscOptions";
export { verifyMinMaxValue } from "./verifyMinMaxValues";
export { saveToLocalStorageAndUpdateDisplay } from "./saveToLocalStorageAndUpdateDisplay";
export { addNewOrderToList } from "./addNewOrderToList";
export { addElementToOrder } from "./addElementToOrder";
export { showOrdersListFromLocalStorage } from "./showOrdersListFromLocalStorage";
export { addOrderToLocalStorage } from "./addOrdersToLocalStorage";
export { updateCurrentOrderDescription } from "./updateCurrentOrderDescription";